"""Editor preference persistence and localized UI text."""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path


class Language(StrEnum):
    ENGLISH = "en"
    SIMPLIFIED_CHINESE = "zh_CN"


LANGUAGE_LABELS: dict[Language, str] = {
    Language.ENGLISH: "English",
    Language.SIMPLIFIED_CHINESE: "简体中文",
}


_ZH_CN = {
    "File": "文件",
    "Edit": "编辑",
    "Entity": "实体",
    "View": "视图",
    "Window": "窗口",
    "Help": "帮助",
    "Create": "创建",
    "New Scene": "新建场景",
    "Open Scene...": "打开场景…",
    "Save": "保存",
    "Save As...": "另存为…",
    "Open Model (MJCF / URDF)...": "打开模型（MJCF / URDF）…",
    "Add Models (MJCF / URDF)...": "添加模型（MJCF / URDF）…",
    "Remove Model": "移除模型",
    "Reload Model": "重新加载模型",
    "Resource Directories": "资源目录",
    "Add Directory...": "添加目录…",
    "Remove": "移除",
    "Quit": "退出",
    "Undo": "撤销",
    "Redo": "重做",
    "Settings...": "设置…",
    "Frame All": "显示全部",
    "Capture Viewport": "截取视口",
    "Scene Helpers": "场景辅助图形",
    "Influence Volumes": "影响范围",
    "Reset Layout": "重置布局",
    "Interaction Reference": "交互参考",
    "About": "关于",
    "Duplicate": "复制",
    "Rename": "重命名",
    "Delete": "删除",
    "Box": "立方体",
    "Sphere": "球体",
    "Cylinder": "圆柱体",
    "Cone": "圆锥体",
    "Plane": "平面",
    "Site": "站点",
    "Point Light": "点光源",
    "Camera": "相机",
    "Untitled": "未命名",
    "Viewport": "视口",
    "Control": "控制",
    "Hierarchy": "层级",
    "Assets": "资源",
    "Inspector": "检查器",
    "Joints": "关节",
    "Keyframes": "关键帧",
    "Plot": "曲线",
    "Stats": "统计",
    "Output": "输出",
    "Settings": "设置",
    "General": "常规",
    "MuJoCo Visuals": "MuJoCo 可视化",
    "Close": "关闭",
    "Sensors": "传感器",
    "Info": "信息",
    "Application": "应用程序",
    "Language": "语言",
    "UI font": "界面字体",
    "CJK font": "中日韩字体",
    "Rendering": "渲染",
    "Interaction": "交互",
    "Shortcuts": "快捷键",
    "Reset shortcuts": "恢复默认快捷键",
    "A key already in use swaps the two actions": "选择已占用的按键时会交换两个动作",
    "Play / Pause": "播放 / 暂停",
    "Frame selection": "聚焦选中项",
    "Move tool": "移动工具",
    "Rotate tool": "旋转工具",
    "World / Body": "世界 / 本体坐标系",
    "Snap": "吸附",
    "Play": "播放",
    "Pause": "暂停",
    "Step": "单步",
    "Pause to step": "暂停后单步",
    "Stop": "停止",
    "Record Viewport": "录制视口",
    "Stop Viewport Recording": "停止视口录制",
    "Move": "移动",
    "Rotate": "旋转",
    "Orbit": "环绕",
    "Pan": "平移",
    "Zoom": "缩放",
    "Frame": "聚焦",
    "Type value": "输入数值",
    "Drag": "拖动",
    "Push": "推移",
    "Twist": "扭转",
    "Running": "运行中",
    "Paused": "已暂停",
    "Static": "静态",
    "Time": "时间",
    "Steps": "步数",
    "No selection": "未选择",
    "Click to show steps": "单击显示步数",
    "Click to show time": "单击显示时间",
    "Right-click to copy exact value": "右键复制精确值",
    "Perturb": "物理扰动",
    "Constrain X": "约束 X 轴",
    "Constrain Y": "约束 Y 轴",
    "Constrain Z": "约束 Z 轴",
    "Fly forward": "向前飞行",
    "Fly backward": "向后飞行",
    "Fly right": "向右飞行",
    "Fly left": "向左飞行",
    "Fly up": "向上飞行",
    "Fly down": "向下飞行",
    "Backend": "后端",
    "Graphics device": "图形设备",
    "Debug view": "调试视图",
    "Labels": "标签",
    "Frames": "坐标架",
    "Gizmo style": "Gizmo 样式",
    "Gizmo orientation": "Gizmo 坐标系",
    "Scene helpers": "场景辅助图形",
    "OpenGL render flags": "OpenGL 渲染开关",
    "3D gizmo": "3D Gizmo",
    "Use the flat 2D overlay": "使用平面 2D 叠加层",
    "World frame (T)": "世界坐标系（T）",
    "position snap (Shift)": "位置吸附（Shift）",
    "rotation snap (Shift)": "旋转吸附（Shift）",
    "rotation tick scale": "旋转刻度大小",
    "view selection padding": "选中项视图留白",
    "1x is a tight fit; larger values move the view farther away": (
        "1x 为紧密适配；数值越大，视图距离越远"
    ),
    "perturb corner radius": "扰动轮廓圆角",
    "scene entity helpers": "场景实体辅助图形",
    "selected influence volumes": "选中实体的影响范围",
    "visual groups": "可视组",
    "BVH depth": "BVH 深度",
    "source": "来源",
    "free": "编辑器相机",
    "missing": "缺失",
    "Return to Editor Camera": "返回编辑器相机",
    "View Through Camera": "切换到此相机",
    "Editor Camera": "编辑器相机",
    "View Camera": "查看相机",
    "Show Camera Preview": "显示相机预览",
    "Lock gizmo while simulation runs": "模拟运行时锁定 Gizmo",
    "gizmo lock": "Gizmo 锁定",
    "camera preview": "相机预览",
    "preview": "预览",
    "Pin": "固定",
    "Pinned": "已固定",
    "Lock": "锁定相机",
    "Locked": "已锁定",
    "model camera follows scene kinematics": "模型相机跟随场景运动",
    "presets": "预设",
    "front": "前",
    "back": "后",
    "left": "左",
    "right": "右",
    "top": "上",
    "bottom": "下",
    "iso": "等轴测",
    "frame all": "显示全部",
    "camera bookmarks": "相机书签",
    "camera bookmark": "相机书签",
    "Stored in": "存储于",
    "Copy all": "全部复制",
    "Copy shown": "复制筛选结果",
    "Copy": "复制",
    "Clear": "清空",
    "Clear search": "清除搜索",
    "Search hierarchy": "搜索层级",
    "Search joints": "搜索关节",
    "Search actuators": "搜索执行器",
    "Name": "名称",
    "Order": "排序",
    "Search output": "搜索输出",
    "Search assets": "搜索资源",
    "Search settings": "搜索设置",
    "messages": "条消息",
    "Copy message": "复制消息",
    "Filter text or component...": "筛选文本或组件…",
    "Filter assets...": "筛选资源…",
    "All levels": "全部级别",
    "No matching joints": "没有匹配的关节",
    "No matching actuators": "没有匹配的执行器",
    "actuators": "执行器",
    "equality": "等式约束",
    "no actuators": "没有执行器",
    "ctrl not produced this frame": "本帧没有控制量",
    "cannot write joint positions": "无法写入关节位置",
    "Pause simulation to edit joint positions": "暂停模拟后才能编辑关节位置",
    "qpos not produced this frame": "本帧没有关节位置数据",
    "no joints": "没有关节",
    "Selected link": "已选连杆",
    "joints total": "个关节",
    "Previous": "上一页",
    "Next": "下一页",
    "page": "页",
    "Using gizmo": "正在使用 Gizmo",
    "Use gizmo": "使用 Gizmo",
    "Choose which direct joint the viewport gizmo edits": "选择视口 Gizmo 要编辑的直属关节",
    "Hinge joint": "旋转关节",
    "Slide joint": "滑动关节",
    "Ball joint": "球形关节",
    "Free joint": "自由关节",
    "dof": "自由度",
    "Mode": "模式",
    "Relative": "相对",
    "Absolute": "绝对",
    "Copy error": "复制错误",
    "Right-click to copy XYZ": "右键复制 XYZ",
    "Click to reset to 0": "单击重置为 0",
    "Read only": "只读",
    "Drag to edit · right-click to copy": "拖动编辑 · 右键复制",
    "Read only · right-click to copy": "只读 · 右键复制",
    "Info and above": "信息及以上",
    "Warnings and errors": "警告和错误",
    "Errors only": "仅错误",
    "orthographic": "正交投影",
    "projection": "投影",
    "persp": "透视",
    "ortho": "正交",
    "Remember precise input choices": "记住精确输入选项",
    "Reuse the last relative/absolute mode and angle unit across editor sessions": (
        "跨编辑器会话沿用上次的相对/绝对模式和角度单位"
    ),
    "position": "位置",
    "target": "目标",
    "up": "上方向",
    "vertical fov": "垂直视场角",
    "near": "近平面",
    "far": "远平面",
    "ortho height": "正交高度",
    "camera view": "相机视图",
    "camera transform": "相机变换",
    "camera projection": "相机投影",
    "camera behavior": "相机行为",
    "light properties": "灯光属性",
    "light transform": "灯光变换",
    "light attenuation": "灯光衰减",
    "light behavior": "灯光行为",
    "enabled": "启用",
    "type": "类型",
    "color": "颜色",
    "intensity": "强度",
    "specular": "高光",
    "ambient": "环境光",
    "texture": "纹理",
    "cast shadow": "投射阴影",
    "position (local)": "位置（局部）",
    "direction (local)": "方向（局部）",
    "range (0 = unlimited)": "范围（0=无限）",
    "range": "范围",
    "0 means unlimited": "0 表示无限",
    "attenuation": "衰减系数",
    "cutoff": "截止角",
    "falloff exponent": "衰减指数",
    "source radius": "光源半径",
    "add a cube texture to illuminate the scene": "添加立方体纹理以照亮场景",
    "appearance": "外观",
    "instance color": "实例颜色",
    "assigned material": "指定材质",
    "inline appearance": "内联外观",
    "asset browser": "资源浏览器",
    "create material": "创建材质",
    "material actions": "材质操作",
    "texture import": "纹理导入",
    "environment textures": "环境纹理",
    "shared material": "共享材质",
    "material properties": "材质属性",
    "base color": "基础颜色",
    "preset": "预设",
    "Presets...": "预设…",
    "emission": "自发光",
    "shininess": "光泽度",
    "reflectance": "反射率",
    "metallic override": "覆盖金属度",
    "metallic": "金属度",
    "roughness override": "覆盖粗糙度",
    "roughness": "粗糙度",
    "texture repeat": "纹理重复",
    "uniform texture scale": "统一纹理缩放",
    "none": "无",
    "Open in Assets": "在资源面板中打开",
    "New material": "新建材质",
    "Duplicate material": "复制材质",
    "Import texture": "导入纹理",
    "Import cube texture": "导入立方体纹理",
    "Import skybox texture": "导入天空盒纹理",
    "Create or assign a shared material to edit its properties": (
        "创建或指定共享材质后才能编辑其属性"
    ),
    "geometry shape and resource": "几何体形状与资源",
    "geometry dimensions": "几何体尺寸",
    "geometry type": "几何体类型",
    "resource": "资源",
    "resource actions": "资源操作",
    "changes": "更改",
    "import": "导入",
    "Import and assign mesh": "导入并指定网格",
    "Import and assign height field": "导入并指定高度场",
    "contact properties": "接触属性",
    "friction (slide spin roll)": "摩擦（滑动 / 旋转 / 滚动）",
    "contact dimension": "接触维度",
    "collision type mask": "碰撞类型掩码",
    "collision affinity mask": "碰撞匹配掩码",
    "contact priority": "接触优先级",
    "contact margin": "接触边距",
    "contact gap": "接触间隙",
    "solver mix": "求解器混合系数",
    "solver reference": "求解器参考参数",
    "impedance min / max / width": "阻抗最小值 / 最大值 / 宽度",
    "impedance midpoint / power": "阻抗中点 / 幂次",
    "adhesion": "黏附力",
    "surface linear velocity": "表面线速度",
    "surface angular velocity": "表面角速度",
    "mass, group, and fluid": "质量、分组与流体",
    "visual group": "可视组",
    "mass source": "质量来源",
    "density": "密度",
    "inertia distribution": "惯量分布",
    "ellipsoid fluid interaction": "椭球流体交互",
    "fluid blunt / slender / angular": "流体系数：钝体 / 细长体 / 角向",
    "fluid Kutta / Magnus": "流体系数：Kutta / Magnus",
    "transform": "变换",
    "rotation": "旋转",
    "velocity": "速度",
    "linear velocity": "线速度",
    "angular velocity": "角速度",
    "body inertial and dynamics": "本体惯性与动力学",
    "inertia mode": "惯性模式",
    "auto from geoms": "由几何体自动计算",
    "diagonal": "对角惯量",
    "full tensor": "完整惯性张量",
    "mass": "质量",
    "inertial position": "惯性位置",
    "inertial rotation": "惯性旋转",
    "diagonal inertia": "对角惯量",
    "tensor xx / yy / zz": "张量 xx / yy / zz",
    "tensor xy / xz / yz": "张量 xy / xz / yz",
    "gravity compensation": "重力补偿",
    "mocap body": "动作捕捉本体",
    "sleep policy": "休眠策略",
    "automatic": "自动",
    "never": "从不",
    "allowed": "允许",
    "initially asleep": "初始休眠",
    "Mass and inertia are derived from attached geoms": "质量和惯量由附属几何体计算",
    "Body-frame rotation of diagonal principal axes; full tensors derive this rotation": (
        "对角主轴相对本体坐标系的旋转；完整张量会自动推导此旋转"
    ),
    "joint properties": "关节属性",
    "advanced joint properties": "高级关节属性",
    "axis": "轴",
    "Axis is expressed in the body frame": "该轴使用本体坐标系表示",
    "limited": "启用限位",
    "limit angle": "限位角度",
    "damping": "阻尼",
    "stiffness": "刚度",
    "qpos address": "qpos 地址",
    "group": "分组",
    "armature": "附加转子惯量",
    "friction loss": "摩擦损耗",
    "reference": "参考位置",
    "spring reference": "弹簧参考位置",
    "limit margin": "限位边距",
    "limit solver reference": "限位求解器参考参数",
    "limit impedance min / max / width": "限位阻抗最小值 / 最大值 / 宽度",
    "limit impedance midpoint / power": "限位阻抗中点 / 幂次",
    "friction solver reference": "摩擦求解器参考参数",
    "friction impedance min / max / width": "摩擦阻抗最小值 / 最大值 / 宽度",
    "friction impedance midpoint / power": "摩擦阻抗中点 / 幂次",
    "actuator force limit": "执行器力限位",
    "actuator force range": "执行器力范围",
    "actuator gravity compensation": "执行器重力补偿",
    "Auto enables the limit when a valid range is authored; unlimited ignores the range": (
        "自动模式在范围有效时启用限位；无限制模式忽略该范围"
    ),
    "MuJoCo sleep policies apply only to movable root bodies": (
        "MuJoCo 休眠策略仅适用于可移动的根本体"
    ),
    "Pause the simulation to edit model body properties": "暂停模拟后才能编辑模型本体属性",
    "Apply": "应用",
    "Revert": "还原",
    "Apply rebuilds the model once": "应用时仅重建一次模型",
    "Joint gizmo": "关节 Gizmo",
    "nothing selected": "未选择任何对象",
    "click an object in the viewport or the Hierarchy panel": "在视口或层级面板中单击对象",
    "node id": "节点 ID",
    "object id": "对象 ID",
    "body": "本体",
    "posable": "可变换",
    "not pickable": "不可拾取",
    "yes": "是",
    "no": "否",
    "no pose this frame": "本帧没有位姿数据",
    "gizmo hidden": "Gizmo 已隐藏",
    "body frame": "本体坐标系",
    "world frame": "世界坐标系",
    "material": "材质",
    "2D": "2D",
    "Add Child": "添加子项",
    "Add Component...": "添加组件…",
    "Add path item": "添加路径项",
    "Add the referenced model elements first": "请先添加引用的模型元素",
    "Apply Dimensions": "应用尺寸",
    "Apply Placement": "应用放置",
    "Assign to Selected Geometry": "指定给选中几何体",
    "Backend info": "后端信息",
    "Body": "本体",
    "Cancel": "取消",
    "Capture Snapshot": "捕获快照",
    "Capture the current state to create the first keyframe.": "捕获当前状态以创建第一个关键帧。",
    "Clear take": "清除录制",
    "Copy details": "复制详情",
    "Corner radius": "圆角半径",
    "Create Material": "创建材质",
    "Creates an unbound material asset for later assignment.": "创建一个可稍后指定的未绑定材质资源。",
    "Cube": "立方体",
    "Debug": "调试",
    "Decimal MuJoCo conaffinity bitmask": "MuJoCo conaffinity 十进制位掩码",
    "Decimal MuJoCo contype bitmask": "MuJoCo contype 十进制位掩码",
    "Delete from Model": "从模型中删除",
    "Deleted camera bookmark": "已删除相机书签",
    "Discard": "放弃",
    "Documentation": "文档",
    "Double-click to load": "双击加载",
    "Down": "下移",
    "Edit MJCF Source...": "编辑 MJCF 源码…",
    "Edit Placement": "编辑放置",
    "Elapsed": "已用时间",
    "Endpoints apply only to capsule and cylinder sites": "端点仅适用于胶囊体和圆柱体站点",
    "Entities": "实体",
    "File operation failed": "文件操作失败",
    "Gizmo": "Gizmo",
    "Height-field import size": "高度场导入尺寸",
    "Helpers": "辅助图形",
    "Import Height Field...": "导入高度场…",
    "Import Mesh...": "导入网格…",
    "Import Texture...": "导入纹理…",
    "Input": "输入",
    "Keep mode/unit": "保留模式和单位",
    "Keyframe state is no longer available": "关键帧状态已不可用",
    "Move playhead": "移动播放头",
    "Switch angle unit": "切换角度单位",
    "Load": "加载",
    "Loaded camera bookmark": "已加载相机书签",
    "Loading": "正在加载",
    "Locate...": "定位…",
    "Locked to avoid accidental model rebuilds.": "已锁定，以免意外重建模型。",
    "MJCF Source": "MJCF 源码",
    "Missing Resources": "资源缺失",
    "MjSpec validates and recompiles the model when changes are applied.": "应用更改时，MjSpec 会校验并重新编译模型。",
    "Model Component": "模型组件",
    "Model Components": "模型组件",
    "Model Keyframes": "模型关键帧",
    "Model placement": "模型放置",
    "MuJoCo geom group used by visibility filters": "可见性筛选使用的 MuJoCo 几何体分组",
    "No matching settings": "没有匹配的设置",
    "No viewport image is available": "没有可用的视口图像",
    "OK": "确定",
    "Open in Plot": "在曲线中打开",
    "Open or close panels from the Window menu; shortcuts are optional.": "可从“窗口”菜单打开或关闭面板；快捷键为可选操作。",
    "Orientation": "坐标系",
    "Overlay size": "叠加层大小",
    "PLAY": "播放",
    "Padding": "留白",
    "Path": "路径",
    "Pause the simulation before editing keyframes": "暂停模拟后才能编辑关键帧",
    "Pause the simulation before editing model components": "暂停模拟后才能编辑模型组件",
    "Pause the simulation before editing model topology": "暂停模拟后才能编辑模型拓扑",
    "Pause the simulation to edit advanced joint properties": "暂停模拟后才能编辑高级关节属性",
    "Pause the simulation to edit model assets": "暂停模拟后才能编辑模型资源",
    "Pause the simulation to edit model contact properties": "暂停模拟后才能编辑模型接触属性",
    "Pause the simulation to edit model geometry properties": "暂停模拟后才能编辑模型几何体属性",
    "Pause the simulation to edit model geometry shape": "暂停模拟后才能编辑模型几何体形状",
    "Pause the simulation to edit site properties": "暂停模拟后才能编辑站点属性",
    "Position": "位置",
    "Positive values use time-constant/damping-ratio format; non-positive values use direct stiffness/damping format": "正值使用时间常数/阻尼比格式；非正值使用直接刚度/阻尼格式",
    "Preview only; applying rebuilds the composed model once.": "当前仅为预览；应用时会重建一次组合模型。",
    "Queued": "排队中",
    "REC": "录制",
    "Read-only entity": "只读实体",
    "Recorded Take": "录制片段",
    "Remove or replace every reference before deleting this asset": "删除此资源前，请移除或替换所有引用",
    "Rename Entity": "重命名实体",
    "Replace File...": "替换文件…",
    "Right-click to reset": "右键重置",
    "Rotation": "旋转",
    "Save as key0": "保存为 key0",
    "Save changes to this file?": "是否保存对此文件的更改？",
    "Save current pose": "保存当前姿态",
    "Save without keyframe": "不保存关键帧",
    "Saved camera bookmark to": "相机书签已保存到",
    "Scale playback, tools, and context hints; right-click to reset": "缩放播放控件、工具和情境提示；右键重置",
    "Search Directory...": "搜索目录…",
    "Select a geometry to assign this asset": "请选择要指定此资源的几何体",
    "Set physical dimensions before importing the PNG.": "导入 PNG 前先设置物理尺寸。",
    "Skybox": "天空盒",
    "Snap · Shift": "吸附 · Shift",
    "Style": "样式",
    "The current pose differs from the model default. Add the current qpos as keyframe key0 in the exported MJCF?": "当前姿态与模型默认值不同。是否在导出的 MJCF 中将当前 qpos 添加为关键帧 key0？",
    "The loader does not expose reliable stage progress.": "加载器不提供可靠的阶段进度。",
    "The selected geometry belongs to a different model": "选中的几何体属于其他模型",
    "This Mojive scene references model files that are no longer available. Locate files individually or search one directory to repair every unambiguous path.": "此 OpenGL 场景引用了已不可用的模型文件。可逐个定位文件，或搜索一个目录以修复所有无歧义路径。",
    "Tick scale": "刻度大小",
    "Toggle the MuJoCo PBR override; disabled uses classic material shading": "切换 MuJoCo PBR 覆盖；关闭时使用传统材质着色",
    "Type": "类型",
    "Unsaved changes": "未保存的更改",
    "Up": "上移",
    "Used": "引用数",
    "View all": "显示全部",
    "Volumes": "范围",
    "World": "世界",
    "ambient light": "环境光",
    "angle": "角度",
    "buckets": "批次",
    "camera data is unavailable": "相机数据不可用",
    "camera view is unavailable": "相机视图不可用",
    "compiled material unavailable": "编译后的材质不可用",
    "component": "分量",
    "contact force": "接触力",
    "cpu ms": "CPU 毫秒",
    "define with endpoints": "使用端点定义",
    "dimension": "维度",
    "draw calls": "绘制调用",
    "elevation": "高程",
    "end": "结束",
    "environment data is unavailable": "环境数据不可用",
    "fog": "雾",
    "frame": "帧",
    "frame cpu": "帧 CPU",
    "frames": "帧",
    "geometry components": "个几何体组件",
    "gpu ms": "GPU 毫秒",
    "haze": "薄雾",
    "headlight": "头灯",
    "height-field dimensions": "高度场尺寸",
    "height-field preview unavailable": "高度场预览不可用",
    "horizon": "地平线",
    "infinite plane": "无限平面",
    "inline": "内联",
    "inline samples": "个内联采样",
    "instances": "实例",
    "joint metadata is unavailable": "关节元数据不可用",
    "key": "关键帧",
    "Key": "键",
    "Shortcut": "快捷键",
    "keyframe": "关键帧",
    "panel": "面板",
    "default": "默认状态",
    "light data is unavailable": "灯光数据不可用",
    "material appearance": "材质外观",
    "material data is unavailable": "材质数据不可用",
    "model": "模型",
    "model elements": "个模型元素",
    "name": "名称",
    "no GPU timer queries on this machine; cpu column only": "此机器不支持 GPU 计时查询；仅显示 CPU 列",
    "no authored components": "没有已编写的组件",
    "no camera attached to this context": "此上下文未连接相机",
    "no editable model assets": "没有可编辑的模型资源",
    "no editable model keyframes": "没有可编辑的模型关键帧",
    "no geometry": "没有几何体",
    "no geometry on this body": "此本体没有几何体",
    "no joint on this body": "此本体没有关节",
    "no joints to plot": "没有可绘制的关节",
    "no match": "没有匹配项",
    "no matching assets": "没有匹配的资源",
    "no panel set in this context": "此上下文没有面板集合",
    "no per-pass timing from this backend": "此后端未提供逐渲染阶段计时",
    "no sensors": "没有传感器",
    "no sensors to plot": "没有可绘制的传感器",
    "normalized": "归一化范围",
    "not produced this frame": "本帧未生成",
    "nothing pushed yet": "尚未提交任何信息",
    "orthographic projection unavailable": "不支持正交投影",
    "output is unavailable": "输出不可用",
    "panels": "面板",
    "pass": "渲染阶段",
    "recorded frames": "个录制帧",
    "references": "引用",
    "samples": "个采样",
    "scale": "范围",
    "scripts fill this via the viewer's info dict": "脚本通过查看器的 info 字典填充此面板",
    "select type": "选择类型",
    "selected": "个已选项",
    "selected snapshot": "已选快照",
    "showing the first": "仅显示前",
    "site shape and endpoints": "站点形状与端点",
    "skybox": "天空盒",
    "slices": "切片数",
    "snapshots": "个快照",
    "start": "开始",
    "texture type": "纹理类型",
    "time": "时间",
    "triangles": "三角形",
    "uniform scale": "统一缩放",
    "value": "数值",
    "visible nodes; use the filter to narrow": "个可见节点；请使用筛选缩小范围",
    "volumetric": "体积雾",
    "waiting for the next frame (qvel is produced on demand)": "正在等待下一帧（qvel 按需生成）",
    "All": "全部",
    "Link": "连杆",
    "Geom": "几何体",
    "Joint": "关节",
    "Light": "灯光",
    "Robot": "机器人",
    "Flex": "柔性体",
    "Model": "模型",
    "Mesh": "网格",
    "Hfield": "高度场",
    "Texture": "纹理",
    "Material": "材质",
    "Contact": "接触",
    "Actuator": "执行器",
    "Sensor": "传感器",
    "Tendon": "肌腱",
    "Equality": "等式约束",
    "X half-size": "X 半尺寸",
    "Y half-size": "Y 半尺寸",
    "elevation scale": "高程缩放",
    "base depth": "基底深度",
    "Stop Recording": "停止录制",
    "Record New Take": "录制新片段",
    "Stop recording": "停止录制",
    "Record new take": "录制新片段",
    "First frame": "第一帧",
    "Previous frame": "上一帧",
    "Replay": "回放",
    "Next frame": "下一帧",
    "Last frame": "最后一帧",
    "no recorded take": "没有录制片段",
    "state recording unavailable": "状态录制不可用",
    "Capture snapshot": "捕获快照",
    "Pause to edit (Space)": "暂停后编辑（空格）",
    "Previous key": "上一个关键帧",
    "Next key": "下一个关键帧",
    "mouse": "鼠标",
    "keyboard": "键盘",
    "value controls": "数值控件",
    "open": "默认打开",
    "closed": "默认关闭",
    "left drag": "左键拖动",
    "orbit the camera": "环绕相机",
    "right / middle drag, or Shift + left drag": "右键或中键拖动，或 Shift + 左键拖动",
    "pan": "平移",
    "wheel": "滚轮",
    "dolly": "推拉相机",
    "left click": "左键单击",
    "select the object under the cursor": "选择光标下的对象",
    "double-click a gizmo axis or ring": "双击 Gizmo 轴或圆环",
    "enter an exact relative distance or angle": "输入精确的相对距离或角度",
    "Ctrl + left drag": "Ctrl + 左键拖动",
    "push the object; physics reacts (works while running)": "推移对象；物理系统会响应（运行时可用）",
    "Ctrl + right drag": "Ctrl + 右键拖动",
    "twist the object": "扭转对象",
    "drag the view balls (top right)": "拖动右上角视图球",
    "free rotate; click a ball to snap to that view": "自由旋转；单击视图球吸附到对应视角",
    "Space": "空格",
    "pause / resume": "暂停 / 继续",
    "gizmo: translate / rotate": "Gizmo：移动 / 旋转",
    "gizmo: body / world frame": "Gizmo：本体 / 世界坐标系",
    "Shift while using a gizmo": "使用 Gizmo 时按住 Shift",
    "snap to the position or rotation step from Settings": "按设置中的位置或旋转步长吸附",
    "hold X / Y / Z": "按住 X / Y / Z",
    "move the mouse along that gizmo axis; no click required": "沿对应 Gizmo 轴移动鼠标；无需单击",
    "U in precise rotation input": "精确旋转输入中按 U",
    "switch between degrees and radians": "切换角度与弧度",
    "frame the whole scene (eased)": "平滑聚焦整个场景",
    "fly": "飞行",
    "up / down along world Z": "沿世界 Z 轴上移 / 下移",
    "this panel": "此面板",
    "right click": "右键单击",
    "reset to the initial value": "重置为初始值",
    "double click": "双击",
    "copy to the clipboard": "复制到剪贴板",
    "Shift + right click": "Shift + 右键单击",
    "more options (drive gain on a joint slider)": "更多选项（关节滑块的驱动增益）",
    "yaw": "偏航",
    "pitch": "俯仰",
    "distance": "距离",
    "fov_y_deg": "垂直视场角",
    "directional": "平行光",
    "point": "点光源",
    "spot": "聚光灯",
    "area": "面光源",
    "image": "图像光源",
    "Ellipsoid": "椭球体",
    "Capsule": "胶囊体",
    "Full authored primitive dimensions": "完整的已编写图元尺寸",
    "Edit model geometry dimensions in its source": "请在模型源码中编辑几何体尺寸",
    "radius": "半径",
    "auto": "自动",
    "unlimited": "无限制",
    "Volume": "体积",
    "Shell": "壳层",
    "volume": "体积",
    "shell": "壳层",
    "explicit mass": "显式质量",
    "1 · frictionless": "1 · 无摩擦",
    "3 · sliding": "3 · 滑动",
    "4 · sliding + torsional": "4 · 滑动 + 扭转",
    "6 · sliding + torsional + rolling": "6 · 滑动 + 扭转 + 滚动",
    "Playback": "播放控制",
    "Tools": "工具",
    "Hints": "提示",
    "hide": "隐藏",
    "show": "显示",
    "select": "请选择",
    "<default>": "<默认>",
    "does not implement": "不支持",
    "has no orthographic projection": "不支持正交投影",
    "backend refused the change": "渲染后端拒绝了此更改",
    "Import": "导入",
    "Replace": "替换",
    "Loaded": "已加载",
    "Opened": "已打开",
    "Saved": "已保存",
    "Locate": "定位",
    "Add MJCF or URDF models": "添加 MJCF 或 URDF 模型",
    "Open an MJCF or URDF model": "打开 MJCF 或 URDF 模型",
    "Choose a model to add": "选择要添加的模型",
    "Choose an MJCF or URDF model": "选择 MJCF 或 URDF 模型",
    "Save scene": "保存场景",
    "Open Mojive scene": "打开 OpenGL 场景",
    "Add Mojive resource directory": "添加 OpenGL 资源目录",
    "Import mesh": "导入网格",
    "Import PNG height field": "导入 PNG 高度场",
    "PNG height field": "PNG 高度场",
    "PNG texture": "PNG 纹理",
    "Search a directory for missing resources": "在目录中搜索缺失资源",
    "The target geometry is no longer available": "目标几何体已不可用",
    "The current workspace cannot open Mojive scene files": "当前工作区无法打开 OpenGL 场景文件",
    "Unsupported file": "不支持的文件",
    "Select a model or body before creating a site": "创建站点前请先选择模型或本体",
    "New Mojive scene": "新建 OpenGL 场景",
    "Adding model": "正在添加模型",
    "Opening scene": "正在打开场景",
    "Reloading model": "正在重新加载模型",
    "Loading model": "正在加载模型",
    "Viewport capture failed": "视口截图失败",
    "Saved viewport capture to": "视口截图已保存到",
    "Viewport recording is unavailable": "视口录制不可用",
    "Viewport recording failed": "视口录制失败",
    "Recording viewport to": "正在将视口录制到",
    "Viewport recording stopped": "视口录制已停止",
    "viewport frame(s) to": "帧视口画面到",
    "g / r": "g / r",
    "t": "t",
    "f": "f",
    "W A S D": "W A S D",
    "Q / E": "Q / E",
    "F1 / ?": "F1 / ?",
    "All supported models (*.xml, *.mjcf, *.urdf)": "所有支持的模型 (*.xml, *.mjcf, *.urdf)",
    "MuJoCo XML / MJCF (*.xml, *.mjcf)": "MuJoCo XML / MJCF (*.xml, *.mjcf)",
    "URDF (*.urdf)": "URDF (*.urdf)",
    "All files": "所有文件",
    "Mojive scenes (*.mojive.json, *.forge.json)": "Mojive 场景 (*.mojive.json, *.forge.json)",
    "PNG images (*.png)": "PNG 图像 (*.png)",
    "MuJoCo mesh files (*.stl, *.obj, *.msh, *.ply)": "MuJoCo 网格文件 (*.stl, *.obj, *.msh, *.ply)",
    "world": "世界",
    "robot": "机器人",
    "link": "连杆",
    "geom": "几何体",
    "joint": "关节",
    "light": "灯光",
    "camera": "相机",
    "environment": "环境",
    "site": "站点",
    "flex": "柔性体",
    "skin": "蒙皮",
    "actuator": "执行器",
    "constraint": "约束",
    "tendon": "肌腱",
    "contact": "接触",
    "selection": "选中项",
    "rangefinder": "测距仪",
    "hinge": "旋转关节",
    "slide": "滑动关节",
    "ball": "球形关节",
    "shadow": "阴影",
    "wireframe": "线框",
    "reflection": "反射",
    "additive": "加法混合",
    "cull_face": "背面剔除",
    "convexhull": "凸包",
    "activation": "激活状态",
    "static": "静态",
    "flex_face": "柔性体表面",
    "flex_skin": "柔性体蒙皮",
    "flex_vertex": "柔性体顶点",
    "flex_edge": "柔性体边",
    "contactpoint": "接触点",
    "contactforce": "接触力",
    "contactsplit": "接触分解",
    "island": "约束岛",
    "autoconnect": "自动连接",
    "transparent": "透明",
    "com": "质心",
    "inertia": "惯性",
    "scaled_inertia": "缩放惯性",
    "body_bvh": "本体 BVH",
    "mesh_bvh": "网格 BVH",
    "outline": "轮廓",
    "tonemap": "色调映射",
    "msaa": "多重采样",
    "shaded": "着色",
    "albedo": "反照率",
    "normal": "法线",
    "depth": "深度",
    "segment": "分割",
    "idcolor": "ID 颜色",
    "overdraw": "过度绘制",
    "contact point": "接触点",
}


def settings_path() -> Path:
    override = os.environ.get("MOJIVE_SETTINGS")
    if override:
        return Path(override).expanduser()
    if sys.platform == "darwin":
        root = Path.home() / "Library" / "Application Support"
    elif os.name == "nt":
        root = Path(os.environ.get("APPDATA", Path.home() / "AppData" / "Roaming"))
    else:
        root = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return root / "mojive" / "settings.json"


def parse_language(value: Language | str) -> Language:
    if isinstance(value, Language):
        return value
    normalized = str(value).strip().split(":", 1)[0].split(".", 1)[0].replace("-", "_").lower()
    if normalized in {"zh", "zh_cn", "zh_hans", "zh_chs"}:
        return Language.SIMPLIFIED_CHINESE
    if normalized in {"en", "en_us", "en_gb"}:
        return Language.ENGLISH
    raise ValueError(f"Unsupported language: {value}")


def _read_settings(path: Path) -> dict[str, object]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return dict(value) if isinstance(value, dict) else {}
    except (OSError, TypeError, ValueError, json.JSONDecodeError):
        return {}


def _read_language(settings: dict[str, object]) -> Language:
    requested = os.environ.get("MOJIVE_LANGUAGE")
    if requested:
        try:
            return parse_language(requested)
        except ValueError:
            return Language.ENGLISH
    try:
        value = settings.get("language", Language.ENGLISH)
        return parse_language(value)
    except (ValueError, TypeError):
        return Language.ENGLISH


@dataclass
class Localizer:
    language: Language = Language.ENGLISH
    path: Path | None = None
    preferences: dict[str, object] = field(default_factory=dict)

    @classmethod
    def load(cls) -> Localizer:
        path = settings_path()
        preferences = _read_settings(path)
        return cls(_read_language(preferences), path, preferences)

    def text(self, value: str) -> str:
        if self.language is Language.SIMPLIFIED_CHINESE:
            return _ZH_CN.get(value, value)
        return value

    def set_language(self, value: Language | str, *, persist: bool = True) -> None:
        self.language = parse_language(value)
        if persist:
            self.set_preferences({"language": self.language.value})

    def preference(self, name: str, default: object = None) -> object:
        return self.preferences.get(str(name), default)

    def set_preferences(self, values: dict[str, object], *, persist: bool = True) -> None:
        self.preferences.update({str(name): value for name, value in values.items()})
        if not persist or self.path is None:
            return
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            json.dumps(self.preferences, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
