"""Design-reference copy extending the editor's shared language selection."""

from mojive.ui.localization import Language

ZH_CN = {
    "Add": "添加",
    "Simulate": "仿真",
    "Play simulation": "运行仿真",
    "Pause simulation": "暂停仿真",
    "Record simulation": "录制仿真",
    "Simulation playback": "仿真播放",
    "Stop recording": "停止录制",
    "Save locally": "保存到本地",
    "Open saved scene": "打开已保存场景",
    "Export scene JSON": "导出场景 JSON",
    "Pending model edits": "待应用的模型编辑",
    "Applying…": "正在应用…",
    "Pose": "姿态",
    "Cameras": "相机",
    "Statistics": "统计",
    "Timeline": "时间轴",
    "Properties": "属性",
    "Author": "创建",
    "Review": "审阅",
    "Joint study": "关节示例",
    "· Joint scene": "· 关节场景",
    "TRANSFORM": "变换",
    "DISPLAY": "显示",
    "IDENTITY": "标识",
    "SURFACE": "表面",
    "World coordinates": "世界坐标",
    "Visible": "可见",
    "Transform handles": "变换手柄",
    "Restore transform": "恢复变换",
    "Scene authoring": "场景编辑",
    "1 selected": "已选中 1 项",
    "Frame all": "显示整个场景",
    "Search scene": "搜索场景",
    "Persp": "透视",
    "Ortho": "正交",
    "Z up": "Z 轴向上",
    "Signals      Events": "信号      事件",
    "Pose keys": "姿态关键点",
    "MATERIAL LIBRARY": "材质库",
    "Sage ceramic": "鼠尾草绿陶瓷",
    "Amber satin": "琥珀缎面",
    "Slate matte": "石板灰哑光",
    "Coral polymer": "珊瑚聚合物",
    "Surface material": "表面材质",
    "Apply material": "应用材质",
    "JOINT POSE": "关节姿态",
    "Hinge angle": "旋转关节角度",
    "Ball angle": "球关节角度",
    "Slide position": "移动关节位置",
    "VIEW DIRECTION": "视图方向",
    "VIEWPORT LAYERS": "视口图层",
    "SCENE OBJECTS": "场景对象",
    "Joint poses": "关节姿态",
    "Live actuator controls": "执行器控制",
    "ACTUATORS": "执行器",
    "CAPABILITIES": "能力",
    "Reset controls": "重置控制",
    "No actuators in this scene": "当前场景没有执行器",
    "Joint pose editing": "关节姿态编辑",
    "Physics write-back": "物理状态写入",
    "Available": "可用",
    "Open pose editor": "打开姿态编辑器",
    "JOINT VALUES": "关节数值",
    "Appearance, scene interaction and rendering": "界面、场景交互与渲染",
    "GENERAL": "常规",
    "CAMERA": "相机",
    "INTERACTION": "交互",
    "RENDERING": "渲染",
    "RECORDING": "录制",
    "MUJOCO VISUALS": "MuJoCo 可视化",
    "Joint-driven transform; use the Joint tab or the viewport handle.": "该变换由关节控制；请使用关节页或视口手柄。",
    "Dimensions require selecting a geometry in the Scene list.": "修改尺寸前，请在场景列表中选择几何体。",
}


def reference_text(localizer, value):
    if localizer.language is Language.SIMPLIFIED_CHINESE and value in ZH_CN:
        return ZH_CN[value]
    return localizer.text(value)
