"""Production viewport chrome shared by the interactive viewer.

The glyphs share cached G3 corner and stroke geometry. A frame scales and
translates cached local paths before submitting them to ``Draw2D``."""

from .capsules import TOOL_CONTROL_CENTERS as TOOL_CONTROL_CENTERS
from .capsules import _circle_button as _circle_button
from .capsules import _set_viewport_tooltip as _set_viewport_tooltip
from .capsules import _viewport_control_colors as _viewport_control_colors
from .capsules import _viewport_tooltip_padding as _viewport_tooltip_padding
from .capsules import capsule_points as capsule_points
from .capsules import draw_capsule as draw_capsule
from .capsules import draw_overlay_divider as draw_overlay_divider
from .capsules import draw_playback as draw_playback
from .capsules import draw_tool_column as draw_tool_column
from .capsules import localized_viewport_labels as localized_viewport_labels
from .capsules import normalized_overlay_position as normalized_overlay_position
from .capsules import overlay_border_hit as overlay_border_hit
from .capsules import overlay_divider_length as overlay_divider_length
from .capsules import playback_control_centers as playback_control_centers
from .capsules import playback_size as playback_size
from .capsules import positioned_overlay_rect as positioned_overlay_rect
from .capsules import tool_column_size as tool_column_size
from .capsules import viewport_chrome_scale as viewport_chrome_scale
from .glyphs import _dimensions_glyph_geometry as _dimensions_glyph_geometry
from .glyphs import _draw_axis_arrow_glyph as _draw_axis_arrow_glyph
from .glyphs import _move_glyph_path as _move_glyph_path
from .glyphs import _move_glyph_shape as _move_glyph_shape
from .glyphs import _pause_icon as _pause_icon
from .glyphs import _play_icon as _play_icon
from .glyphs import _previous_icon as _previous_icon
from .glyphs import _record_icon as _record_icon
from .glyphs import _recording_options_icon as _recording_options_icon
from .glyphs import _reset_icon as _reset_icon
from .glyphs import _rounded_playback_triangle as _rounded_playback_triangle
from .glyphs import _scaled_reset_glyph as _scaled_reset_glyph
from .glyphs import _snap_glyph_shape as _snap_glyph_shape
from .glyphs import _step_icon as _step_icon
from .glyphs import _tool_icon as _tool_icon
from .glyphs import draw_expand_glyph as draw_expand_glyph
from .glyphs import draw_playback_glyph as draw_playback_glyph
from .glyphs import draw_projection_glyph as draw_projection_glyph
from .glyphs import draw_projection_label as draw_projection_label
from .glyphs import draw_recording_glyph as draw_recording_glyph
from .glyphs import draw_recording_options_glyph as draw_recording_options_glyph
from .glyphs import draw_reset_glyph as draw_reset_glyph
from .glyphs import draw_tool_glyph as draw_tool_glyph
from .glyphs import expand_glyph_path as expand_glyph_path
from .glyphs import reset_glyph_path as reset_glyph_path
from .hints import _hint_groups as _hint_groups
from .hints import _inline_text as _inline_text
from .hints import _key_width as _key_width
from .hints import _keycap as _keycap
from .hints import _mouse_width as _mouse_width
from .hints import _tool_hint_width as _tool_hint_width
from .hints import default_tool_hints as default_tool_hints
from .hints import draw_hint as draw_hint
from .hints import draw_mouse_hint_glyph as draw_mouse_hint_glyph
from .hints import draw_scene_tool_hints as draw_scene_tool_hints
from .hints import draw_tool_hints as draw_tool_hints
from .hints import fitting_tool_hints as fitting_tool_hints
from .hints import hint_size as hint_size
from .hints import keycap_rounding as keycap_rounding
from .hints import mouse_button_geometry as mouse_button_geometry
from .hints import mouse_hint_colors as mouse_hint_colors
from .hints import mouse_wheel_geometry as mouse_wheel_geometry
from .hints import pointer_tool_hint as pointer_tool_hint
from .hints import tool_hints_size as tool_hints_size
from .model import _FRAME_ARROW_CORNER_RADIUS_PT as _FRAME_ARROW_CORNER_RADIUS_PT
from .model import _FRAME_AXES as _FRAME_AXES
from .model import _MOVE_ARROW_BASE as _MOVE_ARROW_BASE
from .model import _MOVE_ARROW_TIP as _MOVE_ARROW_TIP
from .model import _MOVE_ARROW_WING as _MOVE_ARROW_WING
from .model import _MOVE_SHAFT_VISUAL_RATIO as _MOVE_SHAFT_VISUAL_RATIO
from .model import _PROJECTION_HALF_WIDTH_PT as _PROJECTION_HALF_WIDTH_PT
from .model import _PROJECTION_STROKE_PT as _PROJECTION_STROKE_PT
from .model import _ROTATE_HALF_RINGS as _ROTATE_HALF_RINGS
from .model import CAPSULE_SMOOTHING as CAPSULE_SMOOTHING
from .model import CENTER_STEP as CENTER_STEP
from .model import DEFAULT_VIEWPORT_LABELS as DEFAULT_VIEWPORT_LABELS
from .model import DEFAULT_VIEWPORT_OVERLAY_SCALE as DEFAULT_VIEWPORT_OVERLAY_SCALE
from .model import DIVIDER_WIDTH as DIVIDER_WIDTH
from .model import FRAME_LABEL_MAX_WIDTH as FRAME_LABEL_MAX_WIDTH
from .model import HINT_CHROME_SCALE as HINT_CHROME_SCALE
from .model import ICON_RADIUS as ICON_RADIUS
from .model import MAX_VIEWPORT_CAPSULE_SCALE as MAX_VIEWPORT_CAPSULE_SCALE
from .model import MAX_VIEWPORT_OVERLAY_SCALE as MAX_VIEWPORT_OVERLAY_SCALE
from .model import MIN_VIEWPORT_CAPSULE_SCALE as MIN_VIEWPORT_CAPSULE_SCALE
from .model import MIN_VIEWPORT_OVERLAY_SCALE as MIN_VIEWPORT_OVERLAY_SCALE
from .model import OVERLAY_CLIP_PADDING as OVERLAY_CLIP_PADDING
from .model import OVERLAY_GEOMETRY as OVERLAY_GEOMETRY
from .model import PLAYBACK_CHROME_SCALE as PLAYBACK_CHROME_SCALE
from .model import PLAYBACK_CONTROLS as PLAYBACK_CONTROLS
from .model import PLAYBACK_HALF_HEIGHT_PT as PLAYBACK_HALF_HEIGHT_PT
from .model import PLAYBACK_RESET_SCALE as PLAYBACK_RESET_SCALE
from .model import PLAYBACK_STEP_SCALE as PLAYBACK_STEP_SCALE
from .model import RECORDING_OPTIONS_ENVELOPE_SCALE as RECORDING_OPTIONS_ENVELOPE_SCALE
from .model import RECORDING_OPTIONS_GLYPH_SCALE as RECORDING_OPTIONS_GLYPH_SCALE
from .model import RECORDING_OPTIONS_STROKE_SCALE as RECORDING_OPTIONS_STROKE_SCALE
from .model import RESET_GLYPH_SCALE as RESET_GLYPH_SCALE
from .model import SHELL_RADIUS as SHELL_RADIUS
from .model import STATE_RADIUS as STATE_RADIUS
from .model import TOOL_CHROME_SCALE as TOOL_CHROME_SCALE
from .model import TOOL_CONTROLS as TOOL_CONTROLS
from .model import TOOL_GLYPH_SCALE as TOOL_GLYPH_SCALE
from .model import TOOL_GROUP_GAP as TOOL_GROUP_GAP
from .model import TOOL_GROUPS as TOOL_GROUPS
from .model import MouseButtonGeometry as MouseButtonGeometry
from .model import MouseWheelGeometry as MouseWheelGeometry
from .model import OverlayGeometry as OverlayGeometry
from .model import StatusLayout as StatusLayout
from .model import ToolHint as ToolHint
from .model import ViewportControl as ViewportControl
from .model import ViewportLabels as ViewportLabels
from .model import _HintGroup as _HintGroup
from .model import _StatusPerformanceLayout as _StatusPerformanceLayout
from .model import _transform_path as _transform_path
from .model import tool_control_centers as tool_control_centers
from .registry import ToolHintRegistry as ToolHintRegistry
from .registry import ViewportChromeRegistry as ViewportChromeRegistry
from .rotate import _counterclockwise as _counterclockwise
from .rotate import _point_in_polygon as _point_in_polygon
from .rotate import _polygon_difference as _polygon_difference
from .rotate import _rotate_stroke_outline as _rotate_stroke_outline
from .rotate import _rotate_visible_ring_polygons as _rotate_visible_ring_polygons
from .status import _status_performance_layout as _status_performance_layout
from .status import draw_status as draw_status
from .status import format_simulation_metric as format_simulation_metric
from .status import format_simulation_steps as format_simulation_steps
from .status import format_simulation_time as format_simulation_time
