"""Selected entity properties and transform editing."""

from .core import InspectorPanel as InspectorPanel
from .fields import _axis_field as _axis_field
from .fields import _axis_field_min_width as _axis_field_min_width
from .fields import _begin_property_table as _begin_property_table
from .fields import _compact_transform as _compact_transform
from .fields import _format_vector as _format_vector
from .fields import _mix_color as _mix_color
from .fields import _property_button_row as _property_button_row
from .fields import _property_color_edit3 as _property_color_edit3
from .fields import _property_color_edit4 as _property_color_edit4
from .fields import _property_control_row as _property_control_row
from .fields import _property_section as _property_section
from .fields import _property_vector_row as _property_vector_row
from .fields import _vector_fields as _vector_fields
from .fields import _vector_row as _vector_row
from .fields import vector_layout as vector_layout
from .support import _MATERIAL_PRESETS as _MATERIAL_PRESETS
from .support import _MODEL_COMPONENT_CATEGORIES as _MODEL_COMPONENT_CATEGORIES
from .support import _MULTILINE_COMPONENT_FIELDS as _MULTILINE_COMPONENT_FIELDS
from .support import GIZMO_REFUSAL_DRIVEN as GIZMO_REFUSAL_DRIVEN
from .support import GIZMO_REFUSAL_RUNNING as GIZMO_REFUSAL_RUNNING
from .support import _body_pose as _body_pose
from .support import _component_value_editor as _component_value_editor
from .support import _free_velocity as _free_velocity
from .support import _has_free_velocity as _has_free_velocity
from .support import _matching_path_preset as _matching_path_preset
from .support import _nearest_euler_degrees as _nearest_euler_degrees
from .support import _node_pose as _node_pose
from .support import _path_preset_label as _path_preset_label
from .support import _pose_editable as _pose_editable
from .support import _unique_component_name as _unique_component_name
from .support import gizmo_refusal_reason as gizmo_refusal_reason
