#!/usr/bin/env python3
"""Validate constrained SVG icon sources and emit deterministic Draw2D data."""

from __future__ import annotations

import argparse
import pprint
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = ROOT / "design" / "icons" / "ui-icons.svg"
DEFAULT_OUTPUT = ROOT / "output" / "ui_icons_generated.py"
ALLOWED = {"circle", "line", "polygon", "polyline", "rect"}
NUMBERS = re.compile(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?")


def _tag(element: ET.Element) -> str:
    return element.tag.rsplit("}", 1)[-1]


def _numbers(value: str) -> tuple[float, ...]:
    return tuple(float(token) for token in NUMBERS.findall(value))


def _shape(element: ET.Element) -> tuple[str, tuple[float, ...]]:
    tag = _tag(element)
    if tag == "circle":
        values = tuple(float(element.attrib[key]) for key in ("cx", "cy", "r"))
    elif tag == "line":
        values = tuple(float(element.attrib[key]) for key in ("x1", "y1", "x2", "y2"))
    elif tag in {"polygon", "polyline"}:
        values = _numbers(element.attrib["points"])
        if len(values) < 4 or len(values) % 2:
            raise ValueError(f"{tag} needs complete point pairs")
    elif tag == "rect":
        values = tuple(
            float(element.attrib.get(key, "0"))
            for key in ("x", "y", "width", "height", "rx")
        )
    else:
        raise ValueError(f"unsupported SVG element: {tag}")
    return tag, values


def _bounds(shape: tuple[str, tuple[float, ...]]) -> tuple[float, float, float, float]:
    tag, values = shape
    if tag == "circle":
        cx, cy, radius = values
        return cx - radius, cy - radius, cx + radius, cy + radius
    if tag == "line":
        x1, y1, x2, y2 = values
        return min(x1, x2), min(y1, y2), max(x1, x2), max(y1, y2)
    if tag in {"polygon", "polyline"}:
        xs, ys = values[0::2], values[1::2]
        return min(xs), min(ys), max(xs), max(ys)
    x, y, width, height, _radius = values
    return x, y, x + width, y + height


def compile_icons(source: Path) -> dict[str, dict[str, object]]:
    root = ET.parse(source).getroot()
    if _numbers(root.attrib.get("viewBox", "")) != (-10.0, -10.0, 20.0, 20.0):
        raise ValueError('root viewBox must be "-10 -10 20 20"')
    icons: dict[str, dict[str, object]] = {}
    for group in root:
        if _tag(group) != "g":
            raise ValueError("the root may contain icon groups only")
        name = group.attrib.get("id", "")
        if not name or name in icons:
            raise ValueError(f"invalid or duplicate icon id: {name!r}")
        shapes = tuple(_shape(element) for element in group)
        for element, shape in zip(group, shapes, strict=True):
            if _tag(element) not in ALLOWED:
                raise ValueError(f"{name}: unsupported element {_tag(element)}")
            stroke = float(element.attrib.get("stroke-width", group.attrib.get("stroke-width", "0")))
            lo_x, lo_y, hi_x, hi_y = _bounds(shape)
            margin = stroke * 0.5
            if min(lo_x, lo_y) - margin < -10.0 or max(hi_x, hi_y) + margin > 10.0:
                raise ValueError(f"{name}: visible geometry exceeds the shared 20 x 20 box")
        icons[name] = {
            "fill": group.attrib.get("fill", "none"),
            "stroke": group.attrib.get("stroke", "none"),
            "stroke_width": float(group.attrib.get("stroke-width", "0")),
            "shapes": shapes,
        }
    return icons


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    icons = compile_icons(args.source.resolve())
    body = "# Generated by design/tools/compile_svg_icons.py; do not edit.\n\n"
    body += "ICON_VIEW_BOX = (-10.0, -10.0, 20.0, 20.0)\n"
    body += f"ICONS = {pprint.pformat(icons, sort_dicts=True, width=100)}\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body, encoding="utf-8")
    print(f"{len(icons)} icons -> {args.output.resolve()}")


if __name__ == "__main__":
    main()
