find_package(Python 3.10 REQUIRED COMPONENTS Interpreter Development.Module)
foreach(name IN ITEMS nanobind pybind11 robin_map)
    mojive_dependency(${name})
endforeach()
add_library(tsl::robin_map INTERFACE IMPORTED)
set_target_properties(tsl::robin_map PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${robin_map_SOURCE_DIR}/include")
set(NB_USE_SUBMODULE_DEPS OFF CACHE BOOL "" FORCE)
set(PYBIND11_FINDPYTHON ON CACHE BOOL "" FORCE)
add_subdirectory("${nanobind_SOURCE_DIR}" "${nanobind_BINARY_DIR}" EXCLUDE_FROM_ALL)
add_subdirectory("${pybind11_SOURCE_DIR}" "${pybind11_BINARY_DIR}" EXCLUDE_FROM_ALL)
add_library(mojive_binding_workload STATIC bindings/workload.cpp)
set_target_properties(mojive_binding_workload PROPERTIES POSITION_INDEPENDENT_CODE ON)
pybind11_add_module(_mojive_pybind_probe MODULE NO_EXTRAS bindings/pybind.cpp)
nanobind_add_module(_mojive_nanobind_probe NB_STATIC NOMINSIZE NOSTRIP bindings/nanobind.cpp)
foreach(name IN ITEMS _mojive_pybind_probe _mojive_nanobind_probe)
    target_link_libraries(${name} PRIVATE mojive_binding_workload)
    set_target_properties(${name} PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bindings")
endforeach()
