include(FetchContent)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../dependencies.lock.json" dependency_lock)
foreach(name IN ITEMS bgfx bx bimg bgfx_cmake glfw imgui)
    string(JSON url GET "${dependency_lock}" ${name} url)
    string(JSON sha GET "${dependency_lock}" ${name} sha256)
    FetchContent_Declare(${name} URL "${url}" URL_HASH "SHA256=${sha}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    # These repositories are composed below instead of running their top-level projects.
    FetchContent_GetProperties(${name})
    if(NOT ${name}_POPULATED)
        FetchContent_Populate(${name})
    endif()
endforeach()
set(BGFX_DIR "${bgfx_SOURCE_DIR}" CACHE PATH "" FORCE)
set(BX_DIR "${bx_SOURCE_DIR}" CACHE PATH "" FORCE)
set(BIMG_DIR "${bimg_SOURCE_DIR}" CACHE PATH "" FORCE)
set(BGFX_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(BGFX_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BGFX_BUILD_EXAMPLE_COMMON OFF CACHE BOOL "" FORCE)
set(BGFX_INSTALL OFF CACHE BOOL "" FORCE)
set(BGFX_CONFIG_RENDERER_WEBGPU OFF CACHE BOOL "" FORCE)
set(BGFX_CONFIG_VIDEO OFF CACHE BOOL "" FORCE)
set(BGFX_CONFIG_MULTITHREADED ON CACHE BOOL "" FORCE)
set(BGFX_WITH_WAYLAND OFF CACHE BOOL "" FORCE)
add_subdirectory("${bgfx_cmake_SOURCE_DIR}" "${bgfx_cmake_BINARY_DIR}" EXCLUDE_FROM_ALL)
target_compile_definitions(bgfx PRIVATE BGFX_CONFIG_RENDERER_WEBGPU=0)
if(APPLE)
    target_compile_definitions(bgfx PRIVATE BGFX_CONFIG_RENDERER_METAL=1)
elseif(WIN32)
    target_compile_definitions(bgfx PRIVATE BGFX_CONFIG_RENDERER_DIRECT3D12=1)
else()
    target_compile_definitions(bgfx PRIVATE BGFX_CONFIG_RENDERER_VULKAN=1)
endif()

# The upstream shaderc target unconditionally links Tint/Dawn. Build the same
# sources with its supported no-Tint configuration; no vendor sources are patched.
include("${bgfx_cmake_SOURCE_DIR}/cmake/bgfx/3rdparty/spirv-opt.cmake")
include("${bgfx_cmake_SOURCE_DIR}/cmake/bgfx/3rdparty/spirv-cross.cmake")
include("${bgfx_cmake_SOURCE_DIR}/cmake/bgfx/3rdparty/glslang.cmake")
file(GLOB shaderc_sources "${BGFX_DIR}/tools/shaderc/*.cpp" "${BGFX_DIR}/src/shader*.cpp")
add_executable(mojive_shaderc ${shaderc_sources})
target_compile_definitions(mojive_shaderc PRIVATE SHADERC_CONFIG_HAS_TINT=0)
target_link_libraries(mojive_shaderc PRIVATE bx bimg bgfx-vertexlayout glslang spirv-opt spirv-cross)

set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLFW_INSTALL OFF CACHE BOOL "" FORCE)
if(UNIX AND NOT APPLE)
    set(GLFW_BUILD_WAYLAND OFF CACHE BOOL "" FORCE)
    set(GLFW_BUILD_X11 ON CACHE BOOL "" FORCE)
endif()
add_subdirectory("${glfw_SOURCE_DIR}" "${glfw_BINARY_DIR}" EXCLUDE_FROM_ALL)
add_library(mojive_imgui STATIC
    "${imgui_SOURCE_DIR}/imgui.cpp" "${imgui_SOURCE_DIR}/imgui_draw.cpp"
    "${imgui_SOURCE_DIR}/imgui_widgets.cpp" "${imgui_SOURCE_DIR}/imgui_tables.cpp"
    "${imgui_SOURCE_DIR}/backends/imgui_impl_glfw.cpp")
target_include_directories(mojive_imgui PUBLIC "${imgui_SOURCE_DIR}" "${imgui_SOURCE_DIR}/backends")
target_link_libraries(mojive_imgui PRIVATE glfw)
