include("${CMAKE_CURRENT_LIST_DIR}/Python.cmake")
mojive_dependency(pybind11)
set(PYBIND11_FINDPYTHON ON CACHE BOOL "" FORCE)
add_subdirectory("${pybind11_SOURCE_DIR}" "${pybind11_BINARY_DIR}" EXCLUDE_FROM_ALL)
add_library(mojive_binding_workload STATIC bindings/workload.cpp)
set_target_properties(mojive_binding_workload PROPERTIES POSITION_INDEPENDENT_CODE ON)
pybind11_add_module(_mojive_pybind_probe MODULE NO_EXTRAS bindings/pybind.cpp)
nanobind_add_module(_mojive_nanobind_probe NB_STATIC NOMINSIZE NOSTRIP bindings/nanobind.cpp)
foreach(name IN ITEMS _mojive_pybind_probe _mojive_nanobind_probe)
    target_link_libraries(${name} PRIVATE mojive_binding_workload)
    set_target_properties(${name} PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bindings")
endforeach()
