include(FetchContent)
get_filename_component(mojive_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${mojive_root}/3rdparty/dependencies.json" dependency_lock)
function(mojive_dependency name)
    string(JSON source_kind ERROR_VARIABLE missing_kind GET "${dependency_lock}" ${name} source)
    if(NOT missing_kind)
        string(JSON source_path GET "${dependency_lock}" ${name} path)
        set(source_dir "${mojive_root}/${source_path}")
        if(NOT EXISTS "${source_dir}/LICENSE" AND NOT EXISTS "${source_dir}/LICENSE.txt"
           AND NOT EXISTS "${source_dir}/LICENSE.md"
           AND NOT EXISTS "${source_dir}/copying.txt")
            message(FATAL_ERROR "Missing ${name} source. Run: git submodule update --init --depth 1")
        endif()
        set(${name}_SOURCE_DIR "${source_dir}" PARENT_SCOPE)
        set(${name}_BINARY_DIR "${CMAKE_BINARY_DIR}/3rdparty/${name}" PARENT_SCOPE)
        return()
    endif()
    # Comparison-only dependencies remain checksum-locked downloads.
    string(JSON url GET "${dependency_lock}" ${name} url)
    string(JSON sha GET "${dependency_lock}" ${name} sha256)
    FetchContent_Declare(${name} URL "${url}" URL_HASH "SHA256=${sha}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    FetchContent_GetProperties(${name})
    if(NOT ${name}_POPULATED)
        FetchContent_Populate(${name})
    endif()
    set(${name}_SOURCE_DIR "${${name}_SOURCE_DIR}" PARENT_SCOPE)
    set(${name}_BINARY_DIR "${${name}_BINARY_DIR}" PARENT_SCOPE)
endfunction()
mojive_dependency(glm)
set(GLM_BUILD_LIBRARY OFF CACHE BOOL "" FORCE)
set(GLM_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLM_BUILD_INSTALL OFF CACHE BOOL "" FORCE)
add_subdirectory("${glm_SOURCE_DIR}" "${glm_BINARY_DIR}" EXCLUDE_FROM_ALL)
mojive_dependency(spdlog)
set(SPDLOG_BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_PIC ON CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_EXAMPLE OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(SPDLOG_INSTALL OFF CACHE BOOL "" FORCE)
set(SPDLOG_FMT_EXTERNAL OFF CACHE BOOL "" FORCE)
set(SPDLOG_FMT_EXTERNAL_HO OFF CACHE BOOL "" FORCE)
set(SPDLOG_USE_STD_FORMAT OFF CACHE BOOL "" FORCE)
add_subdirectory("${spdlog_SOURCE_DIR}" "${spdlog_BINARY_DIR}" EXCLUDE_FROM_ALL)
if(MOJIVE_BUILD_BGFX)
    foreach(name IN ITEMS bgfx bx bimg bgfx_cmake)
        mojive_dependency(${name})
    endforeach()
    set(BGFX_DIR "${bgfx_SOURCE_DIR}" CACHE PATH "" FORCE)
    set(BX_DIR "${bx_SOURCE_DIR}" CACHE PATH "" FORCE)
    set(BIMG_DIR "${bimg_SOURCE_DIR}" CACHE PATH "" FORCE)
    set(BGFX_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
    set(BGFX_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(BGFX_BUILD_EXAMPLE_COMMON OFF CACHE BOOL "" FORCE)
    set(BGFX_INSTALL OFF CACHE BOOL "" FORCE)
    set(BGFX_CONFIG_RENDERER_WEBGPU OFF CACHE BOOL "" FORCE)
    set(BGFX_CONFIG_VIDEO OFF CACHE BOOL "" FORCE)
    set(BGFX_CONFIG_MULTITHREADED ON CACHE BOOL "" FORCE)
    # This switch selects bgfx's OpenGL EGL platform. Vulkan compiles both
    # surface implementations and selects X11/Wayland from PlatformData at runtime.
    set(BGFX_WITH_WAYLAND OFF CACHE BOOL "" FORCE)
    add_subdirectory("${bgfx_cmake_SOURCE_DIR}" "${bgfx_cmake_BINARY_DIR}" EXCLUDE_FROM_ALL)
    target_compile_definitions(bgfx PRIVATE BGFX_CONFIG_RENDERER_WEBGPU=0
        BGFX_CONFIG_MAX_FRAME_BUFFERS=1024 BGFX_CONFIG_MAX_TEXTURES=8192)
    if(APPLE)
        include("${CMAKE_CURRENT_LIST_DIR}/MetalHeadless.cmake")
        target_compile_definitions(bgfx PRIVATE BGFX_CONFIG_RENDERER_METAL=1)
    elseif(WIN32)
        target_compile_definitions(bgfx PRIVATE BGFX_CONFIG_RENDERER_DIRECT3D12=1)
    else()
        target_compile_definitions(bgfx PRIVATE BGFX_CONFIG_RENDERER_VULKAN=1)
        include("${CMAKE_CURRENT_LIST_DIR}/VulkanHeadless.cmake")
    endif()

    # The upstream shaderc target unconditionally links Tint/Dawn. Build the same
    # sources with its supported no-Tint configuration; no vendor sources are patched.
    include("${bgfx_cmake_SOURCE_DIR}/cmake/bgfx/3rdparty/spirv-opt.cmake")
    include("${bgfx_cmake_SOURCE_DIR}/cmake/bgfx/3rdparty/spirv-cross.cmake")
    include("${bgfx_cmake_SOURCE_DIR}/cmake/bgfx/3rdparty/glslang.cmake")
    file(GLOB shaderc_sources "${BGFX_DIR}/tools/shaderc/*.cpp" "${BGFX_DIR}/src/shader*.cpp")
    add_executable(mojive_shaderc ${shaderc_sources})
    target_compile_definitions(mojive_shaderc PRIVATE SHADERC_CONFIG_HAS_TINT=0)
    target_link_libraries(mojive_shaderc PRIVATE bx bimg bgfx-vertexlayout glslang spirv-opt spirv-cross)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        # Match upstream shaderc's headers for its Linux DXC support.
        target_include_directories(mojive_shaderc PRIVATE
            "${BGFX_DIR}/3rdparty/directx-headers/include/directx"
            "${BGFX_DIR}/3rdparty/directx-headers/include"
            "${BGFX_DIR}/3rdparty/directx-headers/include/wsl/stubs")
    endif()

endif()
if(MOJIVE_BUILD_BGFX OR MOJIVE_BUILD_SDL)
    mojive_dependency(glfw)
    mojive_dependency(imgui)
    set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
    set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(GLFW_INSTALL OFF CACHE BOOL "" FORCE)
    if(UNIX AND NOT APPLE)
        set(GLFW_BUILD_WAYLAND ON CACHE BOOL "" FORCE)
        set(GLFW_BUILD_X11 ON CACHE BOOL "" FORCE)
    endif()
    add_subdirectory("${glfw_SOURCE_DIR}" "${glfw_BINARY_DIR}" EXCLUDE_FROM_ALL)
    if(UNIX AND NOT APPLE)
        include("${CMAKE_CURRENT_LIST_DIR}/GlfwX11.cmake")
        include("${CMAKE_CURRENT_LIST_DIR}/GlfwWayland.cmake")
    endif()
    add_library(mojive_imgui STATIC
        "${imgui_SOURCE_DIR}/imgui.cpp" "${imgui_SOURCE_DIR}/imgui_draw.cpp"
        "${imgui_SOURCE_DIR}/imgui_widgets.cpp" "${imgui_SOURCE_DIR}/imgui_tables.cpp"
        "${imgui_SOURCE_DIR}/backends/imgui_impl_glfw.cpp")
    target_include_directories(mojive_imgui PUBLIC "${imgui_SOURCE_DIR}" "${imgui_SOURCE_DIR}/backends")
    target_link_libraries(mojive_imgui PRIVATE glfw)
endif()
if(MOJIVE_BUILD_SDL)
    mojive_dependency(sdl)
    set(SDL_SHARED OFF CACHE BOOL "" FORCE)
    set(SDL_STATIC ON CACHE BOOL "" FORCE)
    set(SDL_TESTS OFF CACHE BOOL "" FORCE)
    set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
    add_subdirectory("${sdl_SOURCE_DIR}" "${sdl_BINARY_DIR}" EXCLUDE_FROM_ALL)
endif()
