include_guard(GLOBAL)
find_package(Python 3.11 REQUIRED COMPONENTS Interpreter Development.Module)
foreach(name IN ITEMS nanobind robin_map)
    mojive_dependency(${name})
endforeach()
if(NOT TARGET tsl::robin_map)
    add_library(tsl::robin_map INTERFACE IMPORTED GLOBAL)
    set_target_properties(tsl::robin_map PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${robin_map_SOURCE_DIR}/include")
endif()
set(NB_USE_SUBMODULE_DEPS OFF CACHE BOOL "" FORCE)
add_subdirectory("${nanobind_SOURCE_DIR}" "${nanobind_BINARY_DIR}" EXCLUDE_FROM_ALL)
