"""Interactive transform and primitive-dimension gizmo behavior."""

from .core import ObjectGizmo as ObjectGizmo
from .joint_labels import _closest_joint_limit_hit as _closest_joint_limit_hit
from .joint_labels import _draw_joint_value_label as _draw_joint_value_label
from .joint_labels import _hinge_current_tick_hit as _hinge_current_tick_hit
from .joint_labels import _hinge_range_hit as _hinge_range_hit
from .joint_labels import _hinge_range_path_hit as _hinge_range_path_hit
from .joint_labels import _joint_limit_label as _joint_limit_label
from .joint_labels import _joint_limit_tick_rect as _joint_limit_tick_rect
from .joint_labels import _joint_range_handle as _joint_range_handle
from .joint_labels import _point_in_rect as _point_in_rect
from .joint_labels import _same_joint_limit as _same_joint_limit
from .joint_labels import _slide_current_tick_hit as _slide_current_tick_hit
from .joint_labels import _slide_range_hit as _slide_range_hit
from .joint_labels import _slide_range_path_hit as _slide_range_path_hit
from .projection import _basis_from_z as _basis_from_z
from .projection import _clip_line_to_rect as _clip_line_to_rect
from .projection import _clip_segment_to_rect as _clip_segment_to_rect
from .projection import _cursor_plane as _cursor_plane
from .projection import _dashed_line_segments as _dashed_line_segments
from .projection import _joint_frame_available as _joint_frame_available
from .projection import _project_finite_axis_segment as _project_finite_axis_segment
from .projection import _project_rotation_dial as _project_rotation_dial
from .projection import _project_rotation_tick as _project_rotation_tick
from .projection import _projected_line_parameters as _projected_line_parameters
from .projection import _rotation_dial_segments as _rotation_dial_segments
from .projection import _rotation_fill_alpha as _rotation_fill_alpha
from .projection import _rotation_sweep as _rotation_sweep
from .projection import _rotation_tick_length_pt as _rotation_tick_length_pt
from .projection import _RotationDialProjector as _RotationDialProjector
from .projection import _ScreenRotationDialProjector as _ScreenRotationDialProjector
from .projection import _set_camera_from_world as _set_camera_from_world
from .projection import _set_light_from_world as _set_light_from_world
from .projection import _shortest_rotation_sweep as _shortest_rotation_sweep
from .projection import _snap_tick_alpha as _snap_tick_alpha
from .projection import _source_light as _source_light
from .projection import _split_segment_around_interval as _split_segment_around_interval
from .projection import _split_segment_around_point as _split_segment_around_point
from .state import _FULL_TURN as _FULL_TURN
from .state import _JOINT_RANGE_EPSILON as _JOINT_RANGE_EPSILON
from .state import _WORLD_BASIS as _WORLD_BASIS
from .state import DEFAULT_ROTATION_SNAP_DEG as DEFAULT_ROTATION_SNAP_DEG
from .state import DEFAULT_ROTATION_TICK_SCALE as DEFAULT_ROTATION_TICK_SCALE
from .state import DEFAULT_TRANSLATION_SNAP_M as DEFAULT_TRANSLATION_SNAP_M
from .state import DRAG_LAYER as DRAG_LAYER
from .state import JOINT_ACTIVE_DARK_COLOR as JOINT_ACTIVE_DARK_COLOR
from .state import JOINT_COMPLEMENT_ALPHA as JOINT_COMPLEMENT_ALPHA
from .state import JOINT_COMPLEMENT_HOVER_ALPHA as JOINT_COMPLEMENT_HOVER_ALPHA
from .state import JOINT_CURRENT_COLOR as JOINT_CURRENT_COLOR
from .state import JOINT_CURRENT_TICK_PT as JOINT_CURRENT_TICK_PT
from .state import JOINT_DRAG_START_TICK_HALF_PT as JOINT_DRAG_START_TICK_HALF_PT
from .state import JOINT_LIMIT_HIT_PADDING_PT as JOINT_LIMIT_HIT_PADDING_PT
from .state import JOINT_LIMIT_HIT_PT as JOINT_LIMIT_HIT_PT
from .state import JOINT_LIMIT_OUTER_HIT_FRACTION as JOINT_LIMIT_OUTER_HIT_FRACTION
from .state import JOINT_LIMIT_STROKE_HIT_PADDING_PT as JOINT_LIMIT_STROKE_HIT_PADDING_PT
from .state import JOINT_LIMIT_TICK_PT as JOINT_LIMIT_TICK_PT
from .state import JOINT_LOWER_LIMIT_COLOR as JOINT_LOWER_LIMIT_COLOR
from .state import JOINT_PRECISION_DWELL_GRACE_SECONDS as JOINT_PRECISION_DWELL_GRACE_SECONDS
from .state import JOINT_PRECISION_MARGIN_PT as JOINT_PRECISION_MARGIN_PT
from .state import JOINT_PRECISION_MAX_HINGE_SPAN_DEG as JOINT_PRECISION_MAX_HINGE_SPAN_DEG
from .state import JOINT_PRECISION_OFFSET_PT as JOINT_PRECISION_OFFSET_PT
from .state import JOINT_PRECISION_PANEL_HEIGHT_PT as JOINT_PRECISION_PANEL_HEIGHT_PT
from .state import JOINT_PRECISION_REVEAL_DELAY_SECONDS as JOINT_PRECISION_REVEAL_DELAY_SECONDS
from .state import JOINT_PRECISION_REVEAL_GRACE_SECONDS as JOINT_PRECISION_REVEAL_GRACE_SECONDS
from .state import JOINT_PRECISION_TRACK_PT as JOINT_PRECISION_TRACK_PT
from .state import JOINT_PRECISION_TRIGGER_PT as JOINT_PRECISION_TRIGGER_PT
from .state import JOINT_RANGE_COLOR as JOINT_RANGE_COLOR
from .state import JOINT_RANGE_OFFSET_PT as JOINT_RANGE_OFFSET_PT
from .state import JOINT_RANGE_RADIUS as JOINT_RANGE_RADIUS
from .state import JOINT_RANGE_WIDTH_PT as JOINT_RANGE_WIDTH_PT
from .state import JOINT_ROTATION_AXIS_DASH_PT as JOINT_ROTATION_AXIS_DASH_PT
from .state import JOINT_ROTATION_AXIS_GAP_PT as JOINT_ROTATION_AXIS_GAP_PT
from .state import JOINT_SLIDE_ARROW_EXTENT_PT as JOINT_SLIDE_ARROW_EXTENT_PT
from .state import JOINT_SLIDE_ARROW_INSET_PT as JOINT_SLIDE_ARROW_INSET_PT
from .state import JOINT_SLIDE_ARROW_OFFSET_PT as JOINT_SLIDE_ARROW_OFFSET_PT
from .state import JOINT_SLIDE_ARROW_TARGET_PT as JOINT_SLIDE_ARROW_TARGET_PT
from .state import JOINT_SLIDE_ARROW_VISUAL_SCALE as JOINT_SLIDE_ARROW_VISUAL_SCALE
from .state import JOINT_SLIDE_AXIS_HIT_PT as JOINT_SLIDE_AXIS_HIT_PT
from .state import JOINT_UPPER_LIMIT_COLOR as JOINT_UPPER_LIMIT_COLOR
from .state import REASON_NO_SELECTION as REASON_NO_SELECTION
from .state import ROTATION_EDGE_LINEAR_ALPHA as ROTATION_EDGE_LINEAR_ALPHA
from .state import ROTATION_LINEAR_ESCAPE_PT as ROTATION_LINEAR_ESCAPE_PT
from .state import ROTATION_LINEAR_LOCK_PT as ROTATION_LINEAR_LOCK_PT
from .state import ROTATION_TICK_MIN_ALPHA as ROTATION_TICK_MIN_ALPHA
from .state import SLIDE_CARDINAL_ESCAPE_PT as SLIDE_CARDINAL_ESCAPE_PT
from .state import SNAP_TICK_FADE_STEPS as SNAP_TICK_FADE_STEPS
from .state import SNAP_TICK_FULL_STEPS as SNAP_TICK_FULL_STEPS
from .state import TRACKBALL_RAD_PER_PT as TRACKBALL_RAD_PER_PT
from .state import TRANSLATION_GUIDE_RADIUS_PT as TRANSLATION_GUIDE_RADIUS_PT
from .state import JointLimitHit as JointLimitHit
from .state import PreciseGizmoInput as PreciseGizmoInput
from .state import Verdict as Verdict
from .state import _axis_of as _axis_of
from .state import _DimensionTarget as _DimensionTarget
from .state import _format_step as _format_step
from .state import _gizmo_geometry_key as _gizmo_geometry_key
from .state import _HingeAxisProjection as _HingeAxisProjection
from .state import _HingeRangeProjection as _HingeRangeProjection
from .state import _joint_current_tick_color as _joint_current_tick_color
from .state import _joint_drag_label_color as _joint_drag_label_color
from .state import _joint_endpoint_color as _joint_endpoint_color
from .state import _joint_value_at_limit as _joint_value_at_limit
from .state import _JointPrecisionProjection as _JointPrecisionProjection
from .state import _JointRangeState as _JointRangeState
from .state import _JointTarget as _JointTarget
from .state import _screen_segment_distance as _screen_segment_distance
from .state import _SlideRangeProjection as _SlideRangeProjection
from .state import _snap_translation as _snap_translation
from .state import _snap_value as _snap_value
from .state import _with_alpha as _with_alpha
from .state import joint_slide_arrow_polygons as joint_slide_arrow_polygons
from .state import joint_slide_arrow_targets as joint_slide_arrow_targets
from .state import verdict as verdict
